#!/bin/bash
PROXY_SETTING="-x 127.0.0.1:1087"
TOKEN=""
BRANCH=""
BUILD_LIST=""
REGISTRY=""
REGISTRY_NAMESPACE=""
REGISTRY_USER=""
REGISTRY_PASSWD=""
DOCKERFILE_URL=""
APP_INFOS_URL=""
BUILD_SCRIPT=""
DEPLOY_SCRIPT=""
BUILD_EXCLUDE_LIST=""
DEPLOY_EXCLUDE_LIST=""

TRIGGER_URL=""
PIPELINES_URL=""

id=`curl $PROXY_SETTING -s -X POST \
    -F token=$TOKEN \
    -F "ref=$BRANCH" \
    -F "variables[BUILD_LIST]=$BUILD_LIST" \
    -F "variables[REGISTRY]=$REGISTRY" \
    -F "variables[REGISTRY_NAMESPACE]=$REGISTRY_NAMESPACE" \
    -F "variables[REGISTRY_USER]=$REGISTRY_USER" \
    -F "variables[REGISTRY_PASSWD]=$REGISTRY_PASSWD" \
    -F "variables[APP_INFOS_URL]=$APP_INFOS_URL" \
    -F "variables[DOCKERFILE_URL]=$DOCKERFILE_URL" \
    -F "variables[BUILD_SCRIPT]=$BUILD_SCRIPT" \
    -F "variables[DEPLOY_SCRIPT]=$DEPLOY_SCRIPT" \
    -F "variables[BUILD_EXCLUDE_LIST]=$BUILD_EXCLUDE_LIST" \
    -F "variables[DEPLOY_EXCLUDE_LIST]=$DEPLOY_EXCLUDE_LIST" \
    $TRIGGER_URL | jq '.id'`

open $PIPELINES_URL/$id
